config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
  has_many :favorites
  has_many :book_comments
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
  has_many :favorites

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy#フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy#フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  private
  def after_sign_in_path_for(resource)
      user_path(resource)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
      root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])# ログイン時にnameを使用
  end
    def correct_user?(user)
      if current_user.nil?
        return false
      else
        user.id.equal?(current_user.id)
      end
    end 
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_new = Book.new
    @book_comment = @book.book_comments.new(book_comment_params)
    @book_comment.user_id = current_user.id
      if @book_comment.save
        flash[:success] = "Comment was successfully created."
        redirect_to book_path(@book)
      else
        @book_comments = BookComment.where(book_id: @book.id)
        render '/books/show'
      end
  end
  def destroy
    @book_comment = BookComment.find(params[:book_id])
    if @book_comment.user != current_user
      redirect_to request.referer
    end
    @book_comment.destroy
    redirect_to request.referer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,only: [:create,:edit,:update,:destroy,:index,:show]
  def show
  	@book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    screen_user(@book)
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_url, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

    def screen_user(book)
      if book.user.id != current_user.id
        redirect_to books_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    redirect_to request.referer
  end

  private
  def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to books_path
    when 1
      redirect_to book_path(@book)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  def follower
    user = User.find(params[:user_id])
    @users = user.following_user
  end
  def followed
    user = User.find(params[:user_id])
    @users = user.follower_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update]
  def show#アクション名、メソッド
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index#アクション名、メソッド
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end
  
  def edit#アクション名、メソッド
  	@user = User.find(params[:id])
  end

  def update#アクション名、メソッド
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def follows
  end

  def followers
  end

  private
  def user_params#アクション名、メソッド
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
    def screen_user#アクション名、メソッド
      unless params[:id].to_i == current_user.id
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to(book.user) do %>
            <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
            <% end %>
          </td>
          <td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
          <td><%= book.body %></td>
          <!--いいね機能-->
          <td>
            <% if book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(book,
                redirect_id: 0), method: :delete do %>
                <span class="glyphicon glyphicon-heart"><%= book.favorites.count %></span>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(book, redirect_id: 0),method: :post do %>
            <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
              <% end %>
            <% end %>
          </td>
          <!--いいね機能-->
          <!--コメント機能-->
          <td>コメント数：<%= book.book_comments.count %></td>
          <!--コメント機能-->
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
<%= render 'layouts/errors', obj: @book %>
<%= render "newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
|
<%= link_to "Back", books_path, class: "back" %>
</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
			<%= render 'newform', book: @book %>
		</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<%= render 'index', books: @books %>
	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'newform', book: Book.new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<!--いいね機能-->
					<td>
						<% if @book.favorited_by?(current_user) %>
							<%= link_to book_favorites_path(@book,redirect_id: 0), method: :delete do %>
							<span class="glyphicon glyphicon-heart-empty">
								<%= @book.favorites.count %></span>
							<% end %>
						<% else %>
							<%= link_to book_favorites_path(@book,
							redirect_id: 0), method: :post do %>
							<span class="glyphicon glyphicon-heart-empty"><%= @book.favorites.count %></span>
							<% end %>
						<% end %>
					<!--いいね機能-->
					</td>
					<!--コメント機能-->
						<td>コメント数：<%= @book.book_comments.count %></td>
					<!--コメント機能-->
					<% if @book.user == current_user %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				</tr>
				<% end %>
			</table>
			<!--コメント機能-->
			<table class="show-tb">
				<% @book_comments.each do |book_comment| %>
				<tr>
					<td>
						<%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
							<%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
						<%= book_comment.user.name %>
					<% end %>
					</td>
					<td><%= book_comment.comment %></td>
					<% unless current_user != book_comment.user %>
						<td><%= link_to 'Destroy',
						book_book_comments_path(book_comment.id),
						class: 'btn-sm btn-davger', method: :delete %></td>
						<% end %>
				</tr>
				<% end %>
			</table>
			<div class="comment-form">
				<%= form_for [@book, @book_comment] do |f| %>
					<%= f.text_area :comment, size: "90x5" %>
					<%= f.submit '送信' %>
				<% end %>
			</div>
			<!--コメント機能-->
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %>prohibited this obj from being saved:</h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'layouts/header' %>
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/relationships/followed.html.erb
<h2>Follower Users</h2>
<!---->
<% if @users.count > 0 %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/follower.html.erb
<h2>Follow Users</h2>
<% if @users.count > 0 %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<!-- users一覧 -->
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
      <td><%= user.name%></td>
      <!--↓フォロー機能-->
      <td>フォロー数：<%= user.follower.count %></td>
      <td>フォロワー数：<%= user.followed.count %></td>
      <td>
        <!--↓users一覧のユーザーが自分以外のとき-->
        <% if current_user != user %>
          <!--↓自分が該当ユーザーをフォローしているとき-->
          <% if current_user.following?(user) %>
            <%= link_to 'フォロー解除', user_relationships_path(user.id), method: :delete %>
          <!--↑自分が該当ユーザーをフォローしているとき-->
          <!--↓自分が該当ユーザーをフォローしていないとき-->
          <% else %>
            <%= link_to 'フォローする', user_relationships_path(user.id),method: :POST %>
          <% end %>
          <!--↑自分が該当ユーザーをフォローしていないとき-->
        <% end %>
        <!--↑users一覧のユーザーが自分以外のとき-->
      </td>
      <!--↑フォロー機能-->
      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<!-- users一覧 -->

app/views/users/_profile.html.erb
<table class="table">
	<tr>
		<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
	</tr>
	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>フォロー中</th>
		<th><%= link_to user.follower.count, user_follows_path(user) %></th>
	</tr>
	<tr>
		<th>フォロワー</th>
		<th><%= link_to user.followed.count, user_followers_path(user) %></th>
	</tr>
</table>
<!--↓プロフィールが自分でないとき フォローボタン-->
<% if current_user != user %>
	<% if current_user.following?(user) %>
		<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
	<% else %>
		<%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
	<% end %>
<% end %>
<!--↑プロフィールが自分でないとき フォローボタン-->
<!--↓プロフィールが自分のとき 編集ボタン-->
<% if user == current_user %>
	<div class="row">
		<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% end %>
<!--↑プロフィールが自分のとき 編集ボタン-->

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>
  <%= render 'layouts/errors', obj: @user %>

  <div class="field">
  	<%= f.label :name %>
  	<%= f.text_field :name, class: "name" %>
  </div>

  <div class="field">
  	<%= f.label :image %>
  	<%= f.attachment_field :profile_image, class: "user_image" %>
  </div>

  <div class="field">
  	<%= f.label :introduction %>
  	<%= f.text_area :introduction, class: "introduction" %>
  </div>

  <div class="actions">
  	<%= f.submit %>
  </div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>

<div class="col-xs-9">
<h2>Users</h2>
<%= render 'index', users: @users %>
	</div>
</div>

app/views/users/show.html.erb
<dev class="row">
	<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class="col-xs-9">
<h2>Books</h2>
<%= render 'books/index',books: @books %>
	</div>
<!--books一覧 -->
</dev>